### ISSUE TITLE
[REQ] Set license on GH

### ISSUE THREAD

**Issue by forart** [ddennedy/movit#2]
Hi there, this software - such as others from @sesse - is awesome !

Even seems no more developed, we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [Video FXs section](https://github.com/forart/HyMPS/blob/main/VideoFXs.md)), can you please set licensing terms on this git ?

Otherwise, as you can see, it does not generates this label that we need: 

https://flat.badgen.net/github/license/ddennedy/movit/?label=LICENSE

![](https://flat.badgen.net/github/license/ddennedy/movit/?label=LICENSE)

Thanks in advance !

**Comment by ddennedy** [comment]
Please be aware that this is a fork of http://git.sesse.net/movit/. I just updated master branch to get its COPYING file.
